<ul class="icons">
				<!-- <li><a href="http://www.ulb.ac.be/" class="icon ulb"><span class="label">ULB - Université Libre de Bruxelles</span></a></li> -->
				<li><a href="http://wiki.osgeo.org/wiki/Belgium" class="icon osgeobe"><span class="label">OSGEObe</span></a></li>
				<!-- <li><a href="http://igeat.ulb.ac.be/" class="icon igeat"><span class="label">Igeat</span></a></li> -->
				<li><a href="http://www.bruxellesenvironnement.be/" class="icon ibge"><span class="label">Bruxelles Environnement</span></a></li>
			</ul>
			<ul class="copyleft">
				<li><i class="fa fa-copyright fa-flip-horizontal"></i> FOSS4G 2015</li>
				<li><i class="fa fa-facebook-square"></i> <a href="https://www.facebook.com/pages/Foss4g-Belgium/863691603712207" title="Facebook">Facebook </a></li>
				<li><a href="credits.php">Credits</a></li>
			</ul>