            <ul class="icons">
                <li><a href="http://aquaterra.be/" class="icon aquaterra"><span class="label">Aquaterra</span></a></li>
                <li><a href="http://www.champs-libres.coop/" class="icon champs-libres"><span class="label">Champs libres</span></a></li>
				<li><a href="http://cirb.brussels/" class="icon cirb"><span class="label">CIRB</span></a></li>
                <li><a href="http://www.geosparc.com/" class="icon geosparc"><span class="label">Geosparc</span></a></li>
                <li><a href="http://www.gim.be" class="icon gim"><span class="label">GIM</span></a></li>
		<li><a href="http://www.innoviris.be" class="icon innoviris"><span class="label">Innoviris</span></a></li>
                <li><a href="http://www.merkator.com" class="icon merkator"><span class="label">Merkator</span></a></li>
                <li><a href="http://www.opengeode.be" class="icon geode"><span class="label">OpenGeode</span></a></li>
				<li><a href="http://oslandia.com/" class="icon oslandia"><span class="label">Oslandia</span></a></li>
            </ul>

            <ul class="copyleft">
				<li><i class="fa fa-copyright fa-flip-horizontal"></i> FOSS4G 2016</li>
				<li><i class="fa fa-facebook-square"></i> <a href="https://www.facebook.com/pages/Foss4g-Belgium/863691603712207" title="Facebook">Facebook </a></li>
				<li><i class="fa fa-twitter-square"></i> <a href="https://www.twitter.com/foss4gbe" title="Twitter">Twitter </a></li>
				<li><a href="credits.php">Credits</a></li>
			</ul>
