			<ul class="icons">
				<li><a href="https://wiki.osgeo.org/wiki/Belgium" class="sponsor icon osgeobe"><span class="label">OSGeo Belgium</span></a></li>
				<li><a href="https://bosa.belgium.be/fr" class="sponsor icon bosa"><span class="label">BOSA</span></a></li>
				<li><a href="https://www.geopostcodes.com/" class="icon geopostcodes"><span class="label">Geo Postcodes</span></a></li>
				<li><a href="https://www.gim.be/" class="sponsor icon gim"><span class="label">gim</span></a></li>
				<li><a href="https://www.mapbox.com/" class="sponsor icon mapbox"><span class="label">Mapbox</span></a></li>
				<li><a href="https://oslandia.com/" class="icon oslandia"><span class="label">Oslandia</span></a></li>
				<li><a href="https://openstreetmap.be/en/" class="sponsor icon osm"><span class="label">OSM Belgium</span></a></li>
			</ul>

			<ul class="icons">
				<li><a href="https://www.atelier-cartographique.be/" class="sponsor icon small atelier"><span class="label">Atelier</span></a></li>
				<li><a href="https://www.bluesquarehub.com/" class="sponsor icon small bluesquare"><span class="label">Bluesquare</span></a></li>
				<li><a href="https://www.champs-libres.coop/" class="sponsor icon small champs-libres"><span class="label">Champs-Libres</span></a></li>
				<li><a href="https://www.idgeo.fr" class="sponsor icon small idgeo"><span class="label">IDGeo</span></a></li>
				<li><a href="https://www.spacebel.com/" class="sponsor icon small spacebel"><span class="label">Spacebel</span></a></li>
			</ul>


			<ul class="copyleft">
				<li><i class="fa fa-copyright fa-flip-horizontal"></i> FOSS4G Belgium 2022 / State of the Map Belgium 2022</li>
				<li><i class="fa fa-facebook-square"></i> <a href="https://www.facebook.com/pages/Foss4g-Belgium/863691603712207" title="Facebook">Facebook </a></li>
				<li><i class="fa fa-twitter-square"></i> <a href="https://www.twitter.com/foss4gbe" title="Twitter">Twitter </a></li>
				<li><a href="credits.php">Credits</a></li>
			</ul>
