			<ul class="icons">
				<li><a href="http://aquaterra.be/" class="icon aquaterra"><span class="label">Aquaterra</span></a></li>
				<li><a href="http://stedelijke-ontwikkeling.irisnet.be/" class="icon bdu"><span class="label">Bruxelles Développement Urbain</span></a></li>
				<li><a href="http://www.bruxellesenvironnement.be/" class="icon bxlenv"><span class="label">Bruxelles Environnement</span></a></li>
				<li><a href="http://www.champs-libres.coop/" class="icon champs-libres"><span class="label">Champs libres</span></a></li>
				<li><a href="http://cirb.brussels/" class="icon cirb"><span class="label">CIRB</span></a></li>
				<li><a href="http://www.opengeode.be" class="icon geode"><span class="label">Open Geode</span></a></li>
				<li><a href="http://www.geosolutions.be" class="icon geosolutions"><span class="label">Geosolutions</span></a></li>
				<li><a href="http://www.geosparc.com/" class="icon geosparc"><span class="label">Geosparc</span></a></li>
				<li><a href="http://www.geospatialworldforum.org/" class="icon gsw"><span class="label">Geospatial World Forum/span></a></li>
				<li><a href="http://www.gim.be" class="icon gim"><span class="label">GIM</span></a></li>
				<li><a href="http://www.idgeo.fr/" class="icon idgeo"><span class="label">IdGeo</span></a></li>
				<li><a href="http://igeat.ulb.ac.be/" class="icon igeat"><span class="label">ULB Igeat</span></a></li>
				<li><a href="http://www.merkator.be/" class="icon merkator"><span class="label">Merkator</span></a></li>
				<li><a href="http://www.neogeo-online.net/" class="icon neogeo"><span class="label">neogeo</span></a></li>
				<li><a href="http://wiki.osgeo.org/wiki/Belgium" class="icon osgeobe"><span class="label">OSGEObe</span></a></li>
				<li><a href="http://oslandia.com/" class="icon oslandia"><span class="label">Oslandia</span></a></li>
				<li><a href="http://www.my-poppy.eu/" class="icon poppy"><span class="label">Poppy</span></a></li>
				<li><a href="http://www.realdolmen.com" class="icon realdolmen"><span class="label">RealDolmen</span></a></li>
			</ul>
			<ul class="copyleft">
				<li><i class="fa fa-copyright fa-flip-horizontal"></i> FOSS4G 2015</li>
				<li><i class="fa fa-facebook-square"></i> <a href="https://www.facebook.com/pages/Foss4g-Belgium/863691603712207" title="Facebook">Facebook </a></li>
				<li><i class="fa fa-twitter-square"></i> <a href="https://www.twitter.com/foss4gbe" title="Twitter">Twitter </a></li>
				<li><a href="credits.php">Credits</a></li>
			</ul>
