<h1><a href="index.php"><span>FOSS</span>4G</a> <?php echo $lang['SITE_DATATOP']; ?></h1>
				<nav id="nav">
					<ul>
						<li><a href="index.php"><?php echo $lang['MENU_HOME']; ?></a></li>
						<li>
							<a href="" class="icon fa-angle-down"><?php echo $lang['MENU_INFOS']; ?></a>
							<ul>
								<li><a href="about.php"><?php echo $lang['MENU_ABOUT']; ?></a></li>
								<li><a href="call.php"><?php echo $lang['MENU_CALL2']; ?></a></li>
								<li><a href="programme.php"><?php echo $lang['MENU_PROGRAMME']; ?></a></li>									
								<li><a href="infos.php"><?php echo $lang['MENU_PRACTICAL']; ?></a></li>								
								<li><a href="programme.php"><?php echo $lang['MENU_PROGRAM']; ?></a></li>
								<li><a href="sponsors.php">Sponsors</a></li>
								<li><a href="contact.php"><?php echo $lang['MENU_CONTACT']; ?></a></li>
							</ul>
						</li>
						<li>
							<a href="" class="icon fa-angle-down"><?php echo $lang['MENU_LANG']; ?></a>
							<ul>
								<li><a href="<?php echo $lang['URL_INDEX_1']; ?>"><?php echo $lang['URL_NAME_1']; ?></a></li>
								<li><a href="<?php echo $lang['URL_INDEX_2']; ?>"><?php echo $lang['URL_NAME_2']; ?></a></li>
								<li><a href="<?php echo $lang['URL_INDEX_3']; ?>"><?php echo $lang['URL_NAME_3']; ?></a></li>
							</ul>
						</li>
						<li><a href="https://www.facebook.com/pages/Foss4g-Belgium/863691603712207" class="button icon fa-facebook default azul" title="Facebook"><span class="label">Facebook</span></a></li>
						<li><a href="https://twitter.com/foss4gbe" class="button icon fa-twitter default azulito" title="Twitter"><span class="label">Twitter</span></a></li>
					</ul>
				</nav>
		
