name: Freeze and Deploy to GitHub Pages

on:
  push:
    branches: [ b2025 ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Freeze the Flask site
        run: |
          uv run freeze.py

      # ADD CNAME file to the root of the build directory
      # - name: Add CNAME file
      #   run: echo "www.foss4g.be" > ./build/CNAME

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build
